name: food_order_app
description: A food ordering app with animations

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  confetti: ^0.7.0
  http: ^0.13.5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/categories/burgers.jpg
    - assets/images/categories/pizzas.jpg
    - assets/images/categories/sushi.jpg
    - assets/images/categories/desserts.jpg
    - assets/images/products/burger1.jpg
    - assets/images/products/burger2.jpg
    - assets/images/products/pizza1.jpg
    - assets/images/products/pizza2.jpg
